Feature/customer crud
bagaskarala/sigap pull request #32
Opened 2021-04-05 09:58 UTC by michaelr1300

- MIGRATION table customer
- /customer
- Edit, Add, Delete using modal
- Routes for customer pagination

Sample data:
![image](https://user-images.githubusercontent.com/46708593/113562251-fdc35b80-962f-11eb-9698-c8f25ecf8129.png)

2021-04-06 10:49 UTC, bagaskarala commented
@michaelr1300 menu sidebarnya kok gak ada

2021-04-06 10:52 UTC, michaelr1300 commented
Sidebar nya sekalian ada menu untuk invoice gapapa mas?

2021-04-06 10:54 UTC, bagaskarala commented
> Sidebar nya sekalian ada menu untuk invoice gapapa mas?
boleh boleh

@michaelr1300 ini typenya sebaiknya pake lowercase
![image](https://user-images.githubusercontent.com/14112952/113700189-beb10b00-9700-11eb-9e35-7dc0915867fd.png)

2021-04-06 11:17 UTC, bagaskarala commented
@michaelr1300 
oiya kalo pattern-nya sebisa mungkin disamain yang lain gimana?

misal seperti ini untuk method `add`:
https://github.com/bagaskarala/sigap/blob/12d0fee867479cfbf9be079cb1b84913f61811f1/application/modules/library/controllers/Library.php#L21

misal untuk deklarasi rules validasi di model, ga perlu set rules satu, contohnya begini:
https://github.com/bagaskarala/sigap/blob/12d0fee867479cfbf9be079cb1b84913f61811f1/application/modules/library/models/Library_model.php#L5

2021-04-06 11:27 UTC, bagaskarala commented
kalo pake modal jadi kurang bagus jika ada error validasi. kalaupun mau pake modal, harusnya handlenya via ajax semua, biar gak reload dan hilang.
https://user-images.githubusercontent.com/14112952/113703765-79430c80-9705-11eb-9676-0449d9d74148.mp4

2021-04-07 02:05 UTC, michaelr1300 commented on application/modules/customer/controllers/Customer.php
> +            'biasa'        => ' - '
type pakai lowercase

2021-04-07 02:06 UTC, michaelr1300 commented on application/modules/customer/models/Customer_model.php
> +        $data = array();
Validation di modal untuk AJAX

2021-04-07 02:07 UTC, michaelr1300 commented on application/modules/customer/models/Customer_model.php
> +        }
Validation AJAX untuk edit (karena id input berbeda dengan modal Add)

2021-04-07 02:07 UTC, michaelr1300 commented on application/modules/customer/views/index_customer.php
> +                                        <small id="error-name" class="d-none error-message text-danger">Nama wajib diisi!</small>
Error message yang akan ditampilkan saat validation error

2021-04-07 02:30 UTC, michaelr1300 commented on application/modules/customer/models/Customer_model.php
> +        }
Validation rule untuk modal (AJAX)

2021-04-07 02:33 UTC, michaelr1300 commented on application/modules/customer/views/index_customer.php
> +                                        <small id="error-phone-number" class="d-none error-message text-danger">Nomor telepon wajib diisi!</small>
Error message yang akan ditampilkan saat validation error

2021-04-07 02:57 UTC, michaelr1300 commented on application/modules/customer/models/Customer_model.php
> -        return TRUE;
Function dipindah langsung di controller supaya se-pattern dengan fitur yang lain

2021-04-07 03:03 UTC, michaelr1300 commented on application/modules/customer/views/index_customer.php
> +})
Sumbit modal add
contoller akan run validation
- Jika ada validation error, controller return array berisi id yang error. Jquery mencari id yang error dari array, kemudain remove class `d-none` sehingga error message muncul di modal. Saat user submit ulang, error message di hidden kemudian controller cek ulang validation, jika masih ada error maka ditampilkan lagi error message nya
- Jika tidak ada validation error, refresh page

https://user-images.githubusercontent.com/46708593/113804311-835a1f00-9788-11eb-82fb-ca862d38f5eb.mp4

2021-04-07 03:05 UTC, michaelr1300 commented on application/modules/customer/views/index_customer.php
> +})
Submit modal edit, sistemnya sama seperti submit modal add

2021-04-07 03:05 UTC, michaelr1300 commented on application/modules/customer/controllers/Customer.php
> -        $this->form_validation->set_rules('phone-number', 'Nomor HP Customer', 'required');
Validation dipindah ke model

2021-04-07 04:35 UTC, bagaskarala requested changes

2021-04-07 04:35 UTC, bagaskarala commented on application/modules/customer/models/Customer_model.php
> +        $data['inputerror'] = array();
ini dibuat lebih readable ya, misal `input_error` begitu

2021-04-07 04:35 UTC, bagaskarala commented on application/modules/customer/models/Customer_model.php
> +    public function validateModalAdd()
untuk method di php sebaiknya pakai snake_case aja ya biar setara, misal `validate_modal_add`

2021-04-07 04:35 UTC, bagaskarala commented on application/modules/customer/controllers/Customer.php
> +            'biasa'        => ' - '
sebisa mungkin pake english semua ya bair konsisten, `penulis` jadi `author`. 
Lalu `biasa` itu maksudnya apa kok pake `-` ? kalo mau default mungkin pake `default` atau `general`.

2021-04-07 05:33 UTC, michaelr1300 commented on application/modules/customer/controllers/Customer.php
> +            'biasa'        => ' - '
Biasa itu untuk orang umum mas. Di controller diganti jadi `general`

2021-04-07 05:46 UTC, bagaskarala requested changes

2021-04-07 05:46 UTC, bagaskarala commented on application/modules/customer/views/index_customer.php
> +];
@michaelr1300 ini daripada deklarasi ulang, lebih baik pake data dari controller, biar pakai satu sumber data.
```php
$type_options =  array_merge(['' => '- Filter Jenis Customer -'], $customer_type);
```

2021-04-07 06:40 UTC, michaelr1300 commented on application/modules/customer/views/index_customer.php
> +];
Oke mas

2021-04-07 07:14 UTC, merged